language: rust
sudo: true

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev
  - wget https://github.com/facebook/rocksdb/archive/rocksdb-3.8.tar.gz; tar xvf rocksdb-3.8.tar.gz && cd rocksdb-rocksdb-3.8 && make shared_lib; make install

rust:
  - nightly
  - 1.1.0

os:
  - linux
  - osx

script:
  - cargo build
  - cargo test
