[package]

name = "rocksdb"
description = "A Rust wrapper for Facebook's RocksDB embeddable database."
version = "0.0.6"
authors = ["Tyler Neely <t@jujit.su>"]
license = "Apache-2.0"

[features]
default=[]
valgrind=[]
